language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6 
  - 7.0
  - hhvm

before_script:
  - phpenv config-rm xdebug.ini || true
  - php -c php.ini bensh.php
  - php -c php.ini php-performance-benchmarks.php

script: php -c php.ini bensh.php
